"""
Report generator.

Pulls everything SQLite knows about a city -- verified claims with their
citations, the crawl status of every source touched, and any unresolved
gaps -- into structured data. get_report_data() is used by the Streamlit UI
to render native widgets; generate_report_pdf() builds the downloadable PDF
from that same data (via reportlab), so the on-screen view and the download
always agree. generate_report() still produces the plain markdown version,
kept for scripting/CLI use.
"""

import re
from io import BytesIO
from xml.sax.saxutils import escape

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable

from stores.db import get_connection

# Same civic/clinical palette as the Streamlit UI, so the downloaded PDF
# doesn't feel like a different product from the app it came from.
INK = "#1C2B2E"
PRIMARY = "#0B5D6E"
WARN = "#B3452C"
MUTED = "#6B6A63"
BORDER = "#DFDACD"


_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+(?=[A-Z0-9\"'])")


def split_into_bullets(text: str, max_bullets: int = 5) -> list[str]:
    """Breaks a prose excerpt into scannable bullet lines. Best-effort sentence
    splitting (no NLP dependency) -- good enough for cleanly-punctuated article
    text, which is what trafilatura's extraction produces."""
    if not text:
        return []
    sentences = [s.strip() for s in _SENTENCE_SPLIT.split(text.strip()) if s.strip()]
    return sentences[:max_bullets]


def get_report_data(city_name: str) -> dict:
    conn = get_connection()
    try:
        claims = conn.execute(
            "SELECT page_title, claim_text, source_url, created_at FROM claims WHERE city_name = ? ORDER BY created_at",
            (city_name,),
        ).fetchall()
        gaps = conn.execute(
            "SELECT topic, claim_text, source_url, reason FROM gaps WHERE city_name = ? ORDER BY created_at",
            (city_name,),
        ).fetchall()
        sources = conn.execute(
            "SELECT url, status, checked_at FROM sources ORDER BY checked_at",
        ).fetchall()
        profile = conn.execute(
            "SELECT created_at FROM city_profile WHERE city_name = ?", (city_name,)
        ).fetchone()
    finally:
        conn.close()

    return {
        "city_name": city_name,
        "first_researched": profile[0] if profile else None,
        "claims": [
            {"page_title": pt, "text": c, "bullets": split_into_bullets(c), "source_url": u, "created_at": t}
            for pt, c, u, t in claims
        ],
        "gaps": [{"topic": t, "claim": c, "source_url": u, "reason": r} for t, c, u, r in gaps],
        "sources": [{"url": u, "status": s, "checked_at": t} for u, s, t in sources],
    }


def generate_report(city_name: str) -> str:
    data = get_report_data(city_name)

    lines = [f"# CARDIO4Cities Research Report: {city_name}", ""]
    if data["first_researched"]:
        lines.append(f"*First researched: {data['first_researched']}*")
    lines.append("")

    lines.append("## Verified Findings")
    if not data["claims"]:
        lines.append("_No verified findings yet -- run `python -m app.main \"" + city_name + "\"` first._")
    for c in data["claims"]:
        if c["page_title"]:
            lines.append(f"### {c['page_title']}")
        for b in (c["bullets"] or [c["text"]]):
            lines.append(f"- {b}")
        lines.append(f"  - **Source:** {c['source_url']} (verified {c['created_at']})")
        lines.append("")

    lines.append("## Known Gaps & Uncertainty")
    lines.append("_Non-negotiable #8: we surface what we don't know rather than inventing it._")
    lines.append("")
    if not data["gaps"]:
        lines.append("No unresolved gaps recorded for this city.")
    for g in data["gaps"]:
        lines.append(f"- **Topic:** {g['topic']}")
        lines.append(f"  - Reason unresolved: {g['reason']}")
        if g["source_url"]:
            lines.append(f"  - Source attempted: {g['source_url']}")
    lines.append("")

    lines.append("## Source Registry (crawlability audit trail)")
    for s in data["sources"]:
        lines.append(f"- `{s['status']}` — {s['url']} (checked {s['checked_at']})")
    lines.append("")

    lines.append("---")
    lines.append("_Generated by the CARDIO4Cities research pipeline. Every finding above traces to a live source fetched at request time -- nothing here is pre-seeded._")

    return "\n".join(lines)


def _pdf_styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("C4CTitle", parent=base["Title"], textColor=PRIMARY, fontSize=20, spaceAfter=4),
        "meta": ParagraphStyle("C4CMeta", parent=base["Normal"], textColor=MUTED, fontSize=9, spaceAfter=14, fontName="Helvetica-Oblique"),
        "h2": ParagraphStyle("C4CH2", parent=base["Heading2"], textColor=INK, fontSize=13, spaceBefore=14, spaceAfter=4),
        "h2_warn": ParagraphStyle("C4CH2Warn", parent=base["Heading2"], textColor=WARN, fontSize=13, spaceBefore=14, spaceAfter=2),
        "finding_title": ParagraphStyle("C4CFindingTitle", parent=base["Heading3"], textColor=PRIMARY, fontSize=11.5, spaceBefore=10, spaceAfter=3),
        "note": ParagraphStyle("C4CNote", parent=base["Normal"], textColor=MUTED, fontSize=9, fontName="Helvetica-Oblique", spaceAfter=8),
        "body": ParagraphStyle("C4CBody", parent=base["Normal"], textColor=INK, fontSize=10.5, leading=15, spaceAfter=2, alignment=TA_LEFT),
        "citation": ParagraphStyle("C4CCitation", parent=base["Normal"], textColor=MUTED, fontSize=8.5, fontName="Helvetica-Oblique", leftIndent=12, spaceAfter=10),
        "footer": ParagraphStyle("C4CFooter", parent=base["Normal"], textColor=MUTED, fontSize=8, fontName="Helvetica-Oblique", spaceBefore=16),
    }


def _fmt_ts(ts: str | None) -> str:
    """Trims a raw ISO timestamp (with microseconds/timezone) to something readable."""
    if not ts:
        return ""
    return ts[:19].replace("T", " ")


def generate_report_pdf(city_name: str) -> bytes:
    """Builds the downloadable PDF report. Returns raw PDF bytes for st.download_button."""
    data = get_report_data(city_name)
    styles = _pdf_styles()
    story = []

    story.append(Paragraph(f"CARDIO4Cities Research Report", styles["title"]))
    story.append(Paragraph(escape(city_name), ParagraphStyle("City", parent=styles["title"], fontSize=15, textColor=INK)))
    if data["first_researched"]:
        story.append(Paragraph(f"First researched: {escape(_fmt_ts(data['first_researched']))}", styles["meta"]))
    else:
        story.append(Spacer(1, 10))

    story.append(HRFlowable(width="100%", color=BORDER, thickness=1))
    story.append(Paragraph("Verified Findings", styles["h2"]))
    if not data["claims"]:
        story.append(Paragraph(f'No verified findings yet for "{escape(city_name)}".', styles["body"]))
    for c in data["claims"]:
        if c["page_title"]:
            story.append(Paragraph(escape(c["page_title"]), styles["finding_title"]))
        for bullet in (c["bullets"] or [c["text"]]):
            story.append(Paragraph(f"• {escape(bullet)}", styles["body"]))
        story.append(Paragraph(f"source: {escape(c['source_url'])} · verified {escape(_fmt_ts(c['created_at']))}", styles["citation"]))

    story.append(HRFlowable(width="100%", color=BORDER, thickness=1))
    story.append(Paragraph("Known Gaps &amp; Uncertainty", styles["h2_warn"]))
    story.append(Paragraph("We surface what we don't know rather than inventing it.", styles["note"]))
    if not data["gaps"]:
        story.append(Paragraph("No unresolved gaps recorded for this city.", styles["body"]))
    for g in data["gaps"]:
        topic_label = escape(g["topic"].replace("_", " "))
        story.append(Paragraph(f"• <b>{topic_label}</b> — {escape(g['reason'])}", styles["body"]))
        if g["source_url"]:
            story.append(Paragraph(f"attempted source: {escape(g['source_url'])}", styles["citation"]))
        else:
            story.append(Spacer(1, 8))

    story.append(HRFlowable(width="100%", color=BORDER, thickness=1))
    story.append(Paragraph("Source Registry", styles["h2"]))
    story.append(Paragraph("Every source's crawlability status, recorded before any content was fetched.", styles["note"]))

    def _source_table(rows_data):
        rows = [["URL", "Checked"]] + [[s["url"], _fmt_ts(s["checked_at"])] for s in rows_data]
        table = Table(rows, colWidths=[5.0 * inch, 1.4 * inch])
        table.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("TEXTCOLOR", (0, 0), (-1, 0), INK),
            ("TEXTCOLOR", (0, 1), (-1, -1), MUTED),
            ("LINEBELOW", (0, 0), (-1, 0), 0.75, BORDER),
            ("LINEBELOW", (0, 1), (-1, -1), 0.5, BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        return table

    allowed_sources = [s for s in data["sources"] if s["status"] == "allowed"]
    other_sources = [s for s in data["sources"] if s["status"] != "allowed"]

    story.append(Paragraph(f"Allowed ({len(allowed_sources)})", styles["finding_title"]))
    if allowed_sources:
        story.append(_source_table(allowed_sources))
    else:
        story.append(Paragraph("None.", styles["body"]))

    story.append(Paragraph(f"Blocked / Unknown ({len(other_sources)})", ParagraphStyle("BlockedLabel", parent=styles["finding_title"], textColor=WARN)))
    if other_sources:
        story.append(_source_table(other_sources))
    else:
        story.append(Paragraph("None.", styles["body"]))

    story.append(Paragraph(
        "Generated by the CARDIO4Cities research pipeline. Every finding above traces to a live "
        "source fetched at request time — nothing here is pre-seeded.",
        styles["footer"],
    ))

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=LETTER,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch, topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        title=f"CARDIO4Cities Report - {city_name}",
    )
    doc.build(story)
    return buffer.getvalue()

